"use client";

import { useState } from "react";
import { ArrowRight, BarChart3, ChevronRight, Database, FlaskConical, Menu, ShieldCheck, Sparkles, Waves, X } from "lucide-react";

const steps = [
  { number: "01", title: "Align", text: "Respect what was actually knowable on every research date." },
  { number: "02", title: "Construct", text: "Turn market, size, value, momentum, and liquidity into signals." },
  { number: "03", title: "Validate", text: "Stress every result with robust statistics and regime context." },
  { number: "04", title: "Simulate", text: "Rebalance a transparent portfolio and compare it with NGX ASI." },
];

function SignalChart() {
  return <svg className="landing-chart" viewBox="0 0 520 180" preserveAspectRatio="none" aria-label="Illustrative model and benchmark performance chart" role="img"><path d="M0 148 C38 142 54 132 82 137 S123 124 150 130 S188 98 216 106 S255 86 286 92 S329 74 352 80 S388 45 415 54 S458 28 520 12" fill="none" stroke="#9fe870" strokeWidth="4" strokeLinecap="round" /><path d="M0 156 C40 153 68 154 92 146 S130 141 155 143 S198 125 220 130 S260 117 286 120 S332 101 352 107 S392 93 417 96 S464 76 520 68" fill="none" stroke="rgba(255,255,255,.32)" strokeWidth="2" strokeDasharray="5 7" strokeLinecap="round" /><circle cx="520" cy="12" r="5" fill="#9fe870" /></svg>;
}

export function LandingPage() {
  const [menuOpen, setMenuOpen] = useState(false);
  return <main className="landing-page">
    <header className="landing-nav"><a href="/" className="landing-logo"><img src="/factorgraph-ngx.png" alt="FactorGraph NGX" /></a><nav className="landing-links"><a href="#platform">Platform</a><a href="#methodology">Methodology</a><a href="#workflow">Workflow</a></nav><div className="landing-actions"><a className="landing-login" href="/dashboard">Log in</a><a className="button button-primary" href="/dashboard">Open console <ArrowRight size={14} /></a><button className="mobile-menu-button" onClick={() => setMenuOpen((open) => !open)} aria-label={menuOpen ? "Close navigation" : "Open navigation"} aria-expanded={menuOpen}>{menuOpen ? <X size={20} /> : <Menu size={20} />}</button></div>{menuOpen && <nav className="landing-mobile-menu"><a href="#platform" onClick={() => setMenuOpen(false)}>Platform <ChevronRight size={15} /></a><a href="#methodology" onClick={() => setMenuOpen(false)}>Methodology <ChevronRight size={15} /></a><a href="#workflow" onClick={() => setMenuOpen(false)}>Workflow <ChevronRight size={15} /></a></nav>}</header>
    <section className="landing-hero"><div className="landing-hero-copy"><span className="landing-kicker"><span className="kicker-rule" /> NGX QUANTITATIVE RESEARCH</span><h1>See the market<br /><em>through signals.</em></h1><p>FactorGraph NGX gives researchers a reproducible way to construct, validate, and backtest a liquidity-augmented multi-factor model for Nigerian equities.</p><div className="landing-hero-actions"><a className="button button-primary" href="/dashboard">Open research console <ArrowRight size={15} /></a><a className="landing-text-link" href="#methodology">See how it works <ChevronRight size={15} /></a></div><div className="landing-integrity"><ShieldCheck size={16} /><span>Deterministic calculations. Point-in-time data. Research-grade traceability.</span></div></div><div className="landing-hero-visual"><div className="signal-card"><div className="signal-card-top"><div><span className="signal-label">ACTIVE RESEARCH RUN</span><strong>Five-factor baseline</strong></div><span className="signal-status"><i /> COMPLETE</span></div><div className="signal-score"><span>MODEL PERFORMANCE</span><b>+24.6%</b><small>Jan 2019 — Dec 2025</small></div><div className="signal-chart-shell"><div className="chart-y-labels"><span>225</span><span>175</span><span>125</span></div><SignalChart /></div><div className="signal-legend"><span><i className="lime-dot" /> Proposed model</span><span><i className="gray-dot" /> NGX ASI</span></div></div><div className="hero-orbit orbit-one">LIQ</div><div className="hero-orbit orbit-two">HMM</div><div className="hero-orbit orbit-three">PIT</div></div></section>
    <section className="landing-proof"><div><b>183</b><span>eligible equities</span></div><div><b>05</b><span>research factors</span></div><div><b>03</b><span>latent market states</span></div><div><b>01</b><span>reproducible pipeline</span></div></section>
    <section className="landing-dark-section" id="platform"><div className="landing-dark-copy"><span className="landing-kicker light"><span className="kicker-rule" /> THE RESEARCH INSTRUMENT</span><h2>From raw observations<br />to <em>defensible evidence.</em></h2><p>A single research environment for data alignment, factor construction, robust validation, regime detection, stock ranking, and portfolio simulation.</p><a className="dark-link" href="/dashboard">Explore the console <ArrowRight size={15} /></a></div><div className="instrument-grid"><div className="instrument-cell active"><Database size={20} /><b>Data foundation</b><span>Prices, fundamentals, benchmarks, and risk-free rates.</span></div><div className="instrument-cell"><BarChart3 size={20} /><b>Five factor signals</b><span>Market, Size, Value, Momentum, and Liquidity.</span></div><div className="instrument-cell"><Waves size={20} /><b>Regime context</b><span>Three-state Gaussian HMM with posterior probabilities.</span></div><div className="instrument-cell"><FlaskConical size={20} /><b>Experiment memory</b><span>Config, version, seed, and outputs preserved together.</span></div></div></section>
    <section className="landing-method" id="methodology"><div className="method-heading"><span className="landing-kicker"><span className="kicker-rule" /> THE METHOD</span><h2>A clear path from question<br />to portfolio.</h2><p>Each experiment follows the same typed workflow. That consistency is what makes the comparison meaningful.</p></div><div className="method-steps" id="workflow">{steps.map((step) => <div className="method-step" key={step.number}><span>{step.number}</span><div><h3>{step.title}</h3><p>{step.text}</p></div></div>)}</div></section>
    <section className="landing-cta"><div><span className="landing-kicker light"><span className="kicker-rule" /> START WITH THE BASELINE</span><h2>Your next NGX question<br />deserves a <em>traceable answer.</em></h2></div><a className="button landing-cta-button" href="/dashboard">Open the research console <ArrowRight size={15} /></a></section>
    <footer className="landing-footer"><div className="footer-brand"><img src="/factorgraph-ngx.png" alt="FactorGraph NGX" /><span>Academic research environment for the Nigerian Exchange.</span></div><div className="footer-links"><a href="/dashboard">Research console</a><a href="#methodology">Methodology</a><a href="mailto:sammyjayisthename@gmail.com">Contact</a></div><span className="footer-note">Not financial advice · simulated research outputs</span></footer>
  </main>;
}