"""initial research schema

Revision ID: 95f90d6fa00b
Revises:
Create Date: 2026-09-11 21:54:36.405361
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "95f90d6fa00b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("ticker", sa.String(length=20), nullable=False),
        sa.Column("isin", sa.String(length=12), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("sector", sa.String(length=100), nullable=True),
        sa.Column("listing_date", sa.Date(), nullable=True),
        sa.Column("delisting_date", sa.Date(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_companies_isin"), "companies", ["isin"], unique=True)
    op.create_index(op.f("ix_companies_sector"), "companies", ["sector"], unique=False)
    op.create_index(op.f("ix_companies_ticker"), "companies", ["ticker"], unique=True)
    op.create_table(
        "dataset_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("version", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("source", sa.String(length=200), nullable=False),
        sa.Column("coverage_start", sa.Date(), nullable=True),
        sa.Column("coverage_end", sa.Date(), nullable=True),
        sa.Column("manifest", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_dataset_versions_version"), "dataset_versions", ["version"], unique=True
    )
    op.create_table(
        "experiments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("dataset_version", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_experiments_dataset_version"), "experiments", ["dataset_version"], unique=False
    )
    op.create_table(
        "benchmark_observations",
        sa.Column("benchmark_code", sa.String(length=50), nullable=False),
        sa.Column("trading_date", sa.Date(), nullable=False),
        sa.Column("close", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("adjusted_close", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("dataset_version_id", sa.UUID(), nullable=True),
        sa.CheckConstraint("close > 0", name="ck_benchmark_close_positive"),
        sa.ForeignKeyConstraint(
            ["dataset_version_id"],
            ["dataset_versions.id"],
        ),
        sa.PrimaryKeyConstraint("benchmark_code", "trading_date"),
    )
    op.create_index(
        "ix_benchmark_observations_date", "benchmark_observations", ["trading_date"], unique=False
    )
    op.create_table(
        "corporate_actions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("action_date", sa.Date(), nullable=False),
        sa.Column("action_type", sa.String(length=50), nullable=False),
        sa.Column("adjustment_factor", sa.Numeric(precision=20, scale=10), nullable=True),
        sa.Column("cash_amount", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("dataset_version_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "adjustment_factor IS NULL OR adjustment_factor > 0",
            name="ck_corporate_actions_factor_positive",
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["dataset_version_id"],
            ["dataset_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_corporate_actions_company_date",
        "corporate_actions",
        ["company_id", "action_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_corporate_actions_company_id"), "corporate_actions", ["company_id"], unique=False
    )
    op.create_table(
        "fundamental_observations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("fiscal_period", sa.Date(), nullable=False),
        sa.Column("publication_date", sa.Date(), nullable=True),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_date_source", sa.String(length=50), nullable=False),
        sa.Column("book_equity", sa.Numeric(precision=28, scale=6), nullable=True),
        sa.Column("shares_outstanding", sa.Numeric(precision=28, scale=6), nullable=True),
        sa.Column("earnings_per_share", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("pe_ratio", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("dividend_yield", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("revenue", sa.Numeric(precision=28, scale=6), nullable=True),
        sa.Column("net_income", sa.Numeric(precision=28, scale=6), nullable=True),
        sa.Column("total_assets", sa.Numeric(precision=28, scale=6), nullable=True),
        sa.Column("total_liabilities", sa.Numeric(precision=28, scale=6), nullable=True),
        sa.Column("source_document", sa.Text(), nullable=True),
        sa.Column("dataset_version_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "shares_outstanding IS NULL OR shares_outstanding > 0",
            name="ck_fundamentals_shares_positive",
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["dataset_version_id"],
            ["dataset_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "company_id",
            "fiscal_period",
            "publication_date",
            name="uq_fundamentals_company_period_publication",
        ),
    )
    op.create_index(
        op.f("ix_fundamental_observations_company_id"),
        "fundamental_observations",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fundamental_observations_effective_from"),
        "fundamental_observations",
        ["effective_from"],
        unique=False,
    )
    op.create_index(
        "ix_fundamentals_company_effective_from",
        "fundamental_observations",
        ["company_id", "effective_from"],
        unique=False,
    )
    op.create_table(
        "price_observations",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("trading_date", sa.Date(), nullable=False),
        sa.Column("open", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("high", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("low", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("close", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("adjusted_close", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("volume", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("trading_value", sa.Numeric(precision=28, scale=6), nullable=True),
        sa.Column("number_of_transactions", sa.Integer(), nullable=True),
        sa.Column("dataset_version_id", sa.UUID(), nullable=True),
        sa.CheckConstraint("close > 0", name="ck_prices_close_positive"),
        sa.CheckConstraint(
            "trading_value IS NULL OR trading_value >= 0",
            name="ck_prices_trading_value_nonnegative",
        ),
        sa.CheckConstraint("volume IS NULL OR volume >= 0", name="ck_prices_volume_nonnegative"),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["dataset_version_id"],
            ["dataset_versions.id"],
        ),
        sa.PrimaryKeyConstraint("company_id", "trading_date"),
    )
    op.create_index(
        "ix_price_observations_date_company",
        "price_observations",
        ["trading_date", "company_id"],
        unique=False,
    )
    op.create_table(
        "risk_free_observations",
        sa.Column("observation_date", sa.Date(), nullable=False),
        sa.Column("tenor", sa.String(length=50), nullable=False),
        sa.Column("annualized_rate", sa.Numeric(precision=12, scale=8), nullable=False),
        sa.Column("dataset_version_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["dataset_version_id"],
            ["dataset_versions.id"],
        ),
        sa.PrimaryKeyConstraint("observation_date", "tenor"),
    )
    op.create_index(
        "ix_risk_free_observations_date",
        "risk_free_observations",
        ["observation_date"],
        unique=False,
    )
    op.create_table(
        "security_identifiers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("ticker", sa.String(length=20), nullable=False),
        sa.Column("isin", sa.String(length=12), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "company_id", "ticker", "valid_from", name="uq_security_identifier_period"
        ),
    )
    op.create_index(
        op.f("ix_security_identifiers_isin"), "security_identifiers", ["isin"], unique=False
    )
    op.create_index(
        op.f("ix_security_identifiers_ticker"), "security_identifiers", ["ticker"], unique=False
    )
    op.create_index(
        "ix_security_identifiers_ticker_period",
        "security_identifiers",
        ["ticker", "valid_from", "valid_to"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_security_identifiers_ticker_period", table_name="security_identifiers")
    op.drop_index(op.f("ix_security_identifiers_ticker"), table_name="security_identifiers")
    op.drop_index(op.f("ix_security_identifiers_isin"), table_name="security_identifiers")
    op.drop_table("security_identifiers")
    op.drop_index("ix_risk_free_observations_date", table_name="risk_free_observations")
    op.drop_table("risk_free_observations")
    op.drop_index("ix_price_observations_date_company", table_name="price_observations")
    op.drop_table("price_observations")
    op.drop_index("ix_fundamentals_company_effective_from", table_name="fundamental_observations")
    op.drop_index(
        op.f("ix_fundamental_observations_effective_from"), table_name="fundamental_observations"
    )
    op.drop_index(
        op.f("ix_fundamental_observations_company_id"), table_name="fundamental_observations"
    )
    op.drop_table("fundamental_observations")
    op.drop_index(op.f("ix_corporate_actions_company_id"), table_name="corporate_actions")
    op.drop_index("ix_corporate_actions_company_date", table_name="corporate_actions")
    op.drop_table("corporate_actions")
    op.drop_index("ix_benchmark_observations_date", table_name="benchmark_observations")
    op.drop_table("benchmark_observations")
    op.drop_index(op.f("ix_experiments_dataset_version"), table_name="experiments")
    op.drop_table("experiments")
    op.drop_index(op.f("ix_dataset_versions_version"), table_name="dataset_versions")
    op.drop_table("dataset_versions")
    op.drop_index(op.f("ix_companies_ticker"), table_name="companies")
    op.drop_index(op.f("ix_companies_sector"), table_name="companies")
    op.drop_index(op.f("ix_companies_isin"), table_name="companies")
    op.drop_table("companies")
    # ### end Alembic commands ###
